project:
  type: website
  output-dir: docs

website:
  title: "Shane and Scout's Berkeley Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rsvp.qmd
        text: RSVP
      - href: WeddingWeekend.qmd
        text: Wedding Weekend
      - href: VisitingtheEastBay.qmd
        text: Visiting the East Bay
      - href: frivolity.qmd
        text: Frivolity
    right:
      - text: Get in Touch
        menu:
          - text: Email Scout
            href: "<mailto:scoutcleonard@gmail.com>"
          - text: Email Shane
            href: "<mailto:shanedevlin33@gmail.com>"

format:
  html:
    theme: 
      - quartz
      - styles.scss
    scripts:
      - scripts/nav-scroll.js

editor: visual



