project:
  type: website
  output-dir: docs

website:
  title: "Shane and Scout's Berkeley Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: WeddingWeekend.qmd
        text: Wedding Weekend
      - href: VisitingtheEastBay.qmd
        text: Visiting the East Bay

format:
  html:
    theme: 
      - quartz
      - styles.scss
  
editor: visual

