project:
  type: website
  output-dir: docs

website:
  title: "Shane and Scout's Berkeley Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: WeddingWeekend.qmd
        text: Wedding Weekend
      - href: VisitingtheEastBay.qmd
        text: Visiting the East Bay
      - href: photos.qmd
        text: Photos
    right:
      - text: Get in Touch
        menu:
          - text: Email Scout
            href: "scoutcleonard@gmail.com"
          - text: Email Shane
            href: "shanedevlin33@gmail.com"

format:
  html:
    theme: 
      - quartz
      - styles.scss
    scripts:
      - scripts/nav-scroll.js

editor: visual


