project:
  type: website

website:
  title: "Shane and Scout's Berkeley Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: WeddingWeekend.qmd
        text: Wedding Weekend

format:
  html:
    theme: 
      - quartz
      - styles.scss
  
editor: visual

