---
title: "Our Wedding Weekend"
---

-   Thursday, September 11th

    -   4 pm: **Wedding Rehearsal** - [UC Berkeley Botanical Garden Redwood Grove Amphitheatre](https://maps.app.goo.gl/KK8gGJY2njR5Muki8) 🌿
        -   *Shane and Scout's parents, our officiant, Shane and Scout*
    -   6 pm: **Rehearsal Pizza Party** - [Our place](https://maps.app.goo.gl/ZjDJ4quR9V2WwYxH9) 🏡
        -   *Everyone welcome!*

-   Friday, September 12th

    -   Before 2 pm: [**Enjoy the UC Berkeley Botanical Gardens**](https://maps.app.goo.gl/DrgqjsZDUBRq8wD1A)🌺

        -   *Tell them you're visiting for Shane and Scout's wedding to enjoy free admission to one of the world's most diverse plant collections. We hope you'll enjoy nerding out over the flora and taking celebratory photos :)*

    -   2 pm - 4 pm: **Wedding Ceremony** - [UC Berkeley Botanical Garden Redwood Grove Amphitheatre](https://maps.app.goo.gl/KK8gGJY2njR5Muki8) 🧡

        -   D*ress Code: Elevated, California Casual - Our wedding will be relaxed and joyful—please come in something you feel great in. No need for jackets or ties. Think: what you’d wear to a beautiful outdoor dinner with people you love.*

    -   5 pm - 8 pm: **Cocktail Hour and Dinner - TBD**

        -   *More to come!*

-   Saturday, September 13th

    -   1 pm: Join us for a local hike!
